server:
  port: ${COMMUNICATION_SERVICE_PORT:8086}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/mentify}

  datasource:
    url: jdbc:postgresql://${COMMUNICATION_DB_HOST:localhost}:${COMMUNICATION_DB_PORT:5434}/${COMMUNICATION_DB_NAME:communication_db}
    username: ${COMMUNICATION_DB_USERNAME:postgres}
    password: ${COMMUNICATION_DB_PASSWORD:change-me}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

mentify:
  security:
    enabled: true
    principal-claim: preferred_username

logging:
  level:
    root: INFO
    com.mentify: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
